let radius = prompt('Рlease enter the radius for the circle');
let square =(Math.PI*(radius**2));
alert(square);
let distance = prompt('Please enter the distance you want to cover,km');
let time = prompt('Рlease enter your desired travel time,hour');
let speed =( 'Your recommended speed '+distance/time + ' km/h');
alert(speed);
let usd = prompt('Please enter usd');
const cours = ( 0.9589);
let eur =( usd*cours +' eur');
alert(eur);